export const createPineconeIndex = async () => {
  //   const pinecone = new PineconeClient()
  //   const pineconeIndex = pinecone.Index(indexName)
  //   const vectorStore = await PineconeStore.fromExistingIndex(embeddings, {
  //     pineconeIndex,
  //     maxConcurrency: 5,
  //   })
  //   const document1 = {
  //     pageContent: `A mitochondrion (pl. mitochondria) is an organelle found in the cells of most eukaryotes, such as animals, plants and fungi. Mitochondria have a double membrane structure and use aerobic respiration to generate adenosine triphosphate (ATP), which is used throughout the cell as a source of chemical energy.[2] They were discovered by Albert von Kölliker in 1857[3] in the voluntary muscles of insects. Meaning a thread-like granule, the term mitochondrion was coined by Carl Benda in 1898. The mitochondrion is popularly nicknamed the "powerhouse of the cell", a phrase popularized by Philip Siekevitz in a 1957 Scientific American article of the same name.[4]  Some cells in some multicellular organisms lack mitochondria (for example, mature mammalian red blood cells). The multicellular animal Henneguya salminicola is known to have retained mitochondrion-related organelles despite a complete loss of their mitochondrial genome.[5][6][7] A large number of unicellular organisms, such as microsporidia, parabasalids and diplomonads, have reduced or transformed their mitochondria into other structures,[8] e.g. hydrogenosomes and mitosomes.[9] The oxymonads Monocercomonoides, Streblomastix, and Blattamonas have completely lost their mitochondria.[5][10]  Mitochondria are commonly between 0.75 and 3 μm2 in cross section,[11] but vary considerably in size and structure. Unless specifically stained, they are not visible. In addition to supplying cellular energy, mitochondria are involved in other tasks, such as signaling, cellular differentiation, and cell death, as well as maintaining control of the cell cycle and cell growth.[12] Mitochondrial biogenesis is in turn temporally coordinated with these cellular processes.[13][14] Mitochondria have been implicated in several human disorders and conditions, such as mitochondrial diseases,[15] cardiac dysfunction,[16] heart failure[17] and autism.[18]
  //     The number of mitochondria in a cell can vary widely by organism, tissue, and cell type. A mature red blood cell has no mitochondria,[19] whereas a liver cell can have more than 2000.[20][21] The mitochondrion is composed of
  //     compartments that carry out specialized functions. These compartments or regions include the outer membrane,
  //      intermembrane space, inner membrane, cristae, and matrix.  Although most of a eukaryotic cell's DNA is contained in the cell nucleus, the mitochondrion has its own genome ("mitogenome") that is substantially similar to bacterial genomes.[22] This finding has led to general acceptance of the endosymbiotic hypothesis - that free-living prokaryotic ancestors of modern mitochondria permanently fused with eukaryotic cells in the distant past, evolving such that modern animals, plants, fungi, and other eukaryotes are able to respire to generate cellular energy `,
  //     metadata: { source: 'https://example.com' },
  //   }
  //   const document2 = {
  //     pageContent: `A building is 'a structure that has a roof and walls and stands more or less permanently in one place';[1] "there was a three-storey building on the corner"; "it was an imposing edifice". In the broadest interpretation a fence or wall is a building.[2] However, the word structure is used more broadly than building, to include natural and human-made formations[3] and ones that do not have walls; structure is more often used for a fence. Sturgis' Dictionary included that "[building] differs from architecture in excluding all idea of artistic treatment; and it differs from construction in the idea of excluding scientific or highly skilful treatment."[4]
  //     Structural height in technical usage is the height to the highest architectural detail on the building from street level. Spires and masts may or may not be included in this height, depending on how they are classified. Spires and masts used as antennas are not generally included. The distinction between a low-rise and high-rise building is a matter of debate, but generally three stories or less is considered low-rise.[5]`,
  //     metadata: { source: 'https://example.com' },
  //   }
  //   const document4 = {
  //     pageContent: `he 2024 Summer Olympics (French: Jeux olympiques d'été de 2024), officially the Games of the XXXIII Olympiad (French: Jeux de la XXXIIIe olympiade de l'ère moderne) and branded as Paris 2024, were an international multi-sport event held from 26 July to 11 August 2024 in France, with several events started from 24 July. Paris was the host city, with events (mainly football) held in 16 additional cities spread across metropolitan France, including the sailing centre in the second-largest city of France, Marseille, on the Mediterranean Sea, as well as one subsite for surfing in Tahiti, French Polynesia.[4]
  //     Paris was awarded the Games at the 131st IOC Session in Lima, Peru, on 13 September 2017. After multiple withdrawals that left only Paris and Los Angeles in contention, the International Olympic Committee (IOC) approved a process to concurrently award the 2024 and 2028 Summer Olympics to the two remaining candidate cities; both bids were praised for their high technical plans and innovative ways to use a record-breaking number of existing and temporary facilities. Having previously hosted in 1900 and 1924, Paris became the second city ever to host the Summer Olympics three times (after London, which hosted the games in 1908, 1948, and 2012).[5][6]
  //     Paris 2024 marked the centenary of Paris 1924 and Chamonix 1924 (the first Winter Olympics), as well as the sixth Olympic Games hosted by France (three Summer Olympics and three Winter Olympics) and the first with this distinction since the 1992 Winter Games in Albertville. The Summer Games returned to the traditional four-year Olympiad cycle, after the 2020 edition was postponed to 2021 due to the COVID-19 pandemic.
  //     Paris 2024 featured the debut of breaking as an Olympic sport,[7] and was the final Olympic Games held during the IOC presidency of Thomas Bach.[8] The 2024 Games were expected to cost €9 billion.[9][10][11] The opening ceremony was held outside of a stadium for the first time in modern Olympic history, as athletes were paraded by boat along the Seine. Paris 2024 was the first Olympics in history to reach full gender parity on the field of play, with equal numbers of male and female athletes.[12]
  //     The United States topped the medal table for the fourth consecutive Summer Games and 19th time overall, with 40 gold and 126 total medals.[13] China tied with the United States on gold (40),
  //     but finished second due to having fewer silvers; the nation won 91 medals overall.
  //     This is the first time a gold medal tie among the two most successful nations has occurred in Summer Olympic history.[14]
  //     Japan finished third with 20 gold medals and sixth in the overall medal count. Australia finished fourth with 18 gold medals and fifth in the overall medal count.
  //     The host nation, France, finished fifth with 16 gold and 64 total medals, and fourth in the overall medal count. Dominica, Saint Lucia, Cape Verde and Albania won their first-ever Olympic medals, the former two both being gold, with Botswana and Guatemala also winning their first-ever gold medals. The Refugee Olympic Team also won their first-ever medal, a bronze in boxing. At the conclusion of the games, despite some controversies throughout relating to politics, logistics and conditions in the Olympic Village, the Games were considered a success by the press, Parisians and observers.[a] The Paris Olympics broke all-time records for ticket sales,
  //     with more than 9.5 million tickets sold (12.1 million including the Paralympic Games).[15]`,
  //     metadata: { source: 'https://example.com' },
  //   }
  //   const documents = [document1, document2, document4]
  //   await vectorStore.addDocuments(documents, { ids: ['1', '2', '4'] })
  //   console.log('completed')
  // }
}
